version: '3.8'

services:
  postgres_db:
    image: postgres:13
    container_name: motor_price_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docker-network
  app:
    image: node:18
    container_name: motor_price_app
    environment:
      - DATABASE_HOST=postgres_db
      - DATABASE_PORT=${POSTGRES_PORT}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${POSTGRES_DATABASE}
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: ['npm', 'run', 'start:dev']
    depends_on:
      - postgres_db
    networks:
      - docker-network

networks:
  docker-network:

volumes:
  postgres_data:
